TITLE: Gentoo Linux Brasil
TITLE_HTML: Gentoo Linux Brasil
TAGLINE: Site da comunidade brasileira de usuários do Gentoo Linux
AUTHOR: Grupo de usuários Gentoo Linux do Brasil
TIMEZONE: America/Sao_Paulo
POSTS_PER_PAGE: 5
